### ISSUE TITLE
Is it possible to run Llama v2 7B INT8 Quantization model on NPU of S24 ultra ?

### ISSUE THREAD

**Issue by taeyeonlee** [saic-fi/MobileQuant#2]
Dear fwtan,
It's great to run your solution (llama-1.1b-mobilequant-w8a8-s1024-e60-8gen3) on NPU of S24 ultra.
Is it possible to run Llama v2 7B INT8 Quantization model on NPU of S24 ultra, using your solution ?

Best regards,

**Comment by fwtan** [comment]
> Dear fwtan, It's great to run your solution (llama-1.1b-mobilequant-w8a8-s1024-e60-8gen3) on NPU of S24 ultra. Is it possible to run Llama v2 7B INT8 Quantization model on NPU of S24 ultra, using your solution ?
> 
> Best regards,

Unfortunately, not at the moment. Running the Llama 7B model in INT8 exceeds the memory limit imposed by QNN. While it's possible to split the model into multiple graphs and run them in separate threads, this may be a long shot solution, and we currently have no plans to support it.

**Comment by fwtan** [comment]
Feel free to reopen the issue if there are any further questions.
