### ISSUE TITLE
Would there be any issues if the ElementwiseAdd operation is not quantized?

### ISSUE THREAD

**Issue by npu-mi-ji** [saic-fi/MobileQuant#8]
![image](https://github.com/user-attachments/assets/5fc5ed7d-dc2c-433f-ade1-73a2df6fb8d2)

Great job, I noticed that there is no quantization and dequantization operation for the input and output of ElementwiseAdd in the code, as shown in the above figure,  the results of the two lines are directly added. Is there a problem？the quantization on the mobile will quantize the output of embed_token.

**Comment by fwtan** [comment]
> ![image](https://private-user-images.githubusercontent.com/170703434/381377112-5fc5ed7d-dc2c-433f-ade1-73a2df6fb8d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzE2NDcsIm5iZiI6MTczMDYzMTM0NywicGF0aCI6Ii8xNzA3MDM0MzQvMzgxMzc3MTEyLTVmYzVlZDdkLWRjMmMtNDMzZi1hZGUxLTczYTJkZjZmYjhkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxMDU1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmUyMjIxMGRlN2EwNGViZWE5ZjdmZmYwZDYwOWZhYzZhYmNmYzU3MmEzNTU1OTA1M2U2OWI1MDBmZGZmMjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mRSJC7HY14VBW4x55UCrH44T6wYRH_zERnJXkKOuA5Q)
> 
> Great job, I noticed that there is no quantization and dequantization operation for the input and output of ElementwiseAdd in the code, as shown in the above figure, the results of the two lines are directly added. Is there a problem？the quantization on the mobile will quantize the output of embed_token.

The features from the embedding layer (i.e. `embed_token`) were in 8-bit. We found that it has limited impact on the performance, either in the Aimet simulation or the on-device deployment.

The `ElementwiseAdd` for the other skip-connection layers were in 16-bit as they are the input to the Normalization layers.
